language: php

os: linux
dist: xenial

php:
    - '7.4'
    - '8.0'
    - '8.1'
    - '8.2'

branches:
    only:
        - master
        - develop

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=4.4.*

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

#jobs:
#    include:
#        - php: 7.4
#          services: [docker]
#          env: DOCKER_BUILD=true
#        - php: 7.4
#          env: SYMFONY_VERSION=4.4.*
#        - php: 8.0
#          env: SYMFONY_VERSION=4.4.*
#        - php: 7.4
#          env: SYMFONY_VERSION=5.2.*
#    allow_failures:
#        - env: SYMFONY_VERSION=5.2.*

notifications:
    email: samuel.breu@bresam.ch
